services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pantry
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/data:/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: false
